import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <div className={styles.backIcon}>
          <svg
            className={styles.backSvg}
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M17.2445 21.3638C17.6118 21.7675 17.5796 22.3856 17.1703 22.7487C16.7601 23.1103 16.1271 23.0778 15.7583 22.676L6.75637 12.8778C6.41454 12.5028 6.41454 11.9404 6.75637 11.5651L15.7569 1.82399C16.1261 1.42223 16.7589 1.38965 17.1689 1.75126C17.6013 2.13521 17.5928 2.75476 17.2431 3.1362L8.84588 12.2227L17.2445 21.3638Z"
              fill="#212121"
            />
          </svg>
        </div>
        <div className={styles.headerText}>Zenny</div>
      </div>
      <div className={styles.messages}>
        <div className={styles.sentMessage}>I need a car!</div>
        <div className={styles.recievedMessage}>Gotcha.</div>
        <div className={styles.recievedMessage}>
          We have a number of models. Any preference?
        </div>
        <div className={styles.sentMessage}>
          Whatever fits me and the family
        </div>
      </div>
      <div className={styles.messageBox}>
        <input
          className={styles.messageBoxInput}
          type="text"
          title="test"
          placeholder="Ask me anything.."
        />
        <button className={styles.messageBoxButton} type="button">
          o
        </button>
      </div>
    </div>
  );
}
